#!/bin/bash

TYPE=$1
URL=$2
PATH_DOWNLOAD="yt-downloads"
DECOR="+----------------------------------+"

cd ~/Descargas
# con -d verificamos si el archivo es un directorio y si existe
if [[ -d $PATH_DOWNLOAD ]]
then
 echo ""
else
 mkdir "yt-downloads"
fi

# con -z devuelve 0 si la cantidad de caracteres de una cadena es 0
if [[ -z $URL || -z $TYPE ]]
then
	echo $DECOR
	echo "Utiliza: yt [TYPE] [URL]"
 	echo "Example: yt v https://youtube.com/...."
 	echo $DECOR
 	echo "[TYPE]: v(videos) m(mp3)"
 	echo $DECOR
else
 if [[ $TYPE = v ]]
 then
	 youtube-dl -F $URL
  	 echo $DECOR
  	 echo "Selecciona el \"FORMAT CODE\" (formato) que deseas descargar: "
	 read option_user
	 echo $DECOR
	 cd $PATH_DOWNLOAD
	 youtube-dl -f $option_user $URL
  	 echo $DECOR
  	 echo "Guardado en:"
  	 pwd
 else
	 cd $PATH_DOWNLOAD
  	 youtube-dl -f 140 $URL
  	 echo $DECOR
   	 echo "Guardado en:"
  	 pwd
 	 echo $DECOR
 fi
fi
exit
